openapi: 3.0.0
info:
  title: HarbourEats Quests API
  version: 1.0.0
  description: API for managing Quests in HarbourEats platform.
servers:
  - url: https://api.harbour-eats.com/v1
paths:
  /quests/{questId}/join:
    post:
      summary: Join a specific Quest
      parameters:
        - in: path
          name: questId
          required: true
          schema:
            type: integer
          description: ID of the Quest to join
      responses:
        '200':
          description: Quest is joined successfully
        '404':
          description: Quest not found
        '500':
          description: Quest not found
  /quests/active:
    get:
      summary: Retrieve a list of ongoing Quests
      responses:
        '200':
          description: List of ongoing Quests retrieved successfully
  /quests/history:
    get:
      summary: Retrieve a history of completed Quests for a courier
      responses:
        '200':
          description: List of completed Quests retrieved successfully
  /quests/{questId}/details:
    get:
      summary: Retrieve details of a specific Quest
      parameters:
        - in: path
          name: questId
          required: true
          schema:
            type: string
          description: ID of the Quest to retrieve details for
      responses:
        '200':
          description: Quest details retrieved successfully
        '404':
          description: Quest not found